### ISSUE TITLE
Nice project!

### ISSUE THREAD

**Issue by SylvainCorlay** [rjsberry/xtensor-interpolate#1]
Hi @rjsberry, xtensor developer here. @wolfv just came across your project on GitHub. This is really nice work!

If you are interested, we could add your project on the list of related projects in the documentation for xtensor. Also, if you want to drop by, don't hesitate to hop on our gitter chat https://gitter.im/QuantStack/Lobby

**Comment by rjsberry** [comment]
Hi, thanks a lot for the feedback! I'm more than happy for you to refer/link to the project wherever you want. Adding it to your related projects is a huge compliment, so thanks. :smile:
I've been swamped lately so it's not been receiving much love. Perhaps a little more traffic is the motivation I need to keep it alive.
